version: "3.9"
services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - webhook_data:/app/files/
    command: "/app/webhook -hooks hooks.json -verbose"  
volumes: 
  webhook_data:
    external: true
