FROM golang:1.16

WORKDIR /app

ENV WEBHOOK_VERSION 2.8.0
RUN curl -L --silent -o webhook.tar.gz https://github.com/adnanh/webhook/archive/${WEBHOOK_VERSION}.tar.gz \
  && tar -xzf webhook.tar.gz --strip 1 \
  && go build github.com/adnanh/webhook
EXPOSE 9000
COPY hooks.json /app/
COPY testRequest.json /app/
